config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/home', to: 'pages#home'
  post '/home', to: 'pages#create'
  get '/logout', to: 'pages#destroy'
  
  resources :companies do
    member do
      post 'like'
      get '/likes', to: 'companies#user_likes'
    end
  end
  
  resources :users, except: [:new,:index, :destroy]
  get '/register', to: 'users#new'
  
  resources :branches, only: [:new, :create, :show]
  
  
end

app/models/branch.rb
class Branch < ActiveRecord::Base
    has_many :company_branches
    has_many :companies, through: :company_branches
    has_many :users
    validates :name, presence: true, length: { minimum: 2, maximum: 25 }
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
    
    before_action :require_user, except: [:show]
    
    def new
        @branch = Branch.new
    end
    
    def create
        @branch = Branch.new(branch_params)
        if @branch.save
          flash[:success] = "Branch was created successfully"
          redirect_to companies_path
        else
          render 'new'
        end
    end
  
  def show
      @branch = Branch.find(params[:id])
      @companies = @branch.companies.paginate(page: params[:page],per_page: 4)
  end
  
  private
    def branch_params
       params.require(:branch).permit(:name) 
    end
end

app/views/branches/_branch.html.erb
<span class='quiet'><%= link_to branch.name, branch_path(branch) %> </span>

app/views/branches/_form.html.erb
<%= render 'shared/errors', obj: @branch %>

<div class="row">
    <div class = "col-md-6 col-md-offset-3 well" style="background-color: rgba(245, 245, 245, 0.3);">
        <strong><h3 class="text-center">Create New Branch</h3></strong>
      
           <br><br>
        <%= form_for @branch do |f| %>
         <%= f.label :name %>  <%= f.text_field :name %>
         
        <%= f.submit 'Create Branch',class: "btn btn-warning" %>
        <% end %>
    </div>
</div>

app/views/branches/new.html.erb
<div style="padding-top: 50px;">
    <%= render 'layouts/navigationWithoutLogin' %>
</div>

<div>
    
    <div class="row">
        <strong><h3 class="text-center" style="margin-bottom: 10px"></h3></strong>
    </div>
    <img src="/assets/form.jpg" id="mybg" alt="background image">
    <%= render 'form' %>
    
</div>

app/views/branches/show.html.erb
<div style="padding-top: 50px;">
    <%= render 'layouts/navigationWithoutLogin' %>
</div>

<div style="background-image: url('/assets/header.jpg'">
    
<div style="padding-top: 30px;"><h2 class="text-center" style="color: white; margin-bottom: 30px">Companies Recruiting From <%= @branch.name %> Branch</h2></div>

<% @branch.companies.each do |company| %>

<div class="container well">
	<div class="row">
		<div class="row"> 
                    <div class="col-xs-12 col-sm-3 col-md-3">
                        
                            <%= link_to image_tag(company.picture.url,size: "250x250", class: "gravatar img-responsive img-box img-thumbnail"),company_path(company) if company.picture? %>
                        
                    </div> 
                    <div class="col-xs-12 col-sm-9 col-md-9">
                        <div class="pull-right" style="margin-right: 7px; color: #FF4500">
                            <% case company.rating.round(2)  %>
                                <% when 1...2 %>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 20px;"></i>
                                <% when 2...3 %>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 20px;"></i>
                                <% when 3...4 %>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 20px;"></i>
                                <% when 4...5 %>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 20px;"></i>
                                <% when 5 %>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                <% else %>
                                    Not Rated Yet
                            <% end %>
                        </div>
                        <div class="list-group">
                            <div class="list-group-item">
                                <div class="row-picture">
                                    <%= link_to gravatar_for(company.user, size: 100), user_path(company.user)%>
                                </div>
                                <div class="row-content">
                                    <div class="list-group-item-heading">
                                        <%= link_to company.companyname,company_path(company) %>
                                    </div>
                                    <small>
                                        <i class="glyphicon glyphicon-calendar"></i> Arriving on <%= company.date %> 
                                        <br>
                                        <span class="explore"><i class="glyphicon glyphicon-th"></i> <a href="#">Package: <%= company.package %> lpa </a></span>
                                    </small>
                                </div>
                            </div>
                        </div>
                        <p style="word-wrap: break-word; color: #55423E" class="well"><%= company.description %></p>
                        <strong>For <%= render company.branches %> Branch</strong>
                        <div align="right" style="margin-right: 5px"><em>Brought to you by <strong><%= link_to company.user.username,user_path(company.user) %></strong></em></div>
                        
                    </div> 
        </div>
        
    </div>
</div>

<% end %>


<div style="padding-top: 50px;"></div>

</div>
        