config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/home', to: 'pages#home'
  post '/home', to: 'pages#create'
  get '/logout', to: 'pages#destroy'
  
  resources :companies do
    member do
      post 'like'
      get '/likes', to: 'companies#user_likes'
    end
  end
  
  resources :users, except: [:new,:index, :destroy]
  get '/register', to: 'users#new'
  
  resources :branches, only: [:new, :create, :show]
  
  
end

app/models/company.rb
class Company < ActiveRecord::Base
    belongs_to :user
    has_many :likes
    has_many :company_branches
    has_many :branches, through: :company_branches
    validates :user_id, presence: true
    validates :companyname, presence: true, length: { minimum: 3 ,maximum: 100 }
    validates :location, presence: true, length: { minimum: 5, maximum: 300 }
    validates :package, presence: true
    validates :description, presence: true, length: {minimum: 10, maximum: 1000 }
    mount_uploader :picture, PictureUploader
    validate :picture_size
    
     default_scope -> { order(updated_at: :desc) }
    
    def count_one_stars
      self.likes.where(like: 1).size
    end
    
    def count_two_stars
      self.likes.where(like: 2).size
    end
    
    def count_three_stars
      self.likes.where(like: 3).size
    end
    
    def count_four_stars
      self.likes.where(like: 4).size
    end
    
    def count_five_stars
      self.likes.where(like: 5).size
    end
    
    def rating
      ((count_one_stars + 2*count_two_stars + 3*count_three_stars + 4*count_four_stars + 5*count_five_stars)/self.likes.size.to_f).round(1)
    end
    
    private
    def picture_size 
      if picture.size > 5.megabytes
        errors.add(:picture,"should be less than 5MB")
      end
    end
end

app/controllers/companies_controller.rb
require 'mini_magick'
class CompaniesController < ApplicationController
   
   before_action :set_company, only: [:edit,:update,:like, :show, :user_likes]
   before_action :require_user, except: [:like]
   before_action :require_user_likes, only: [:like]
   before_action :require_admin, except: [:index, :show, :like,  :user_likes]
   before_action :require_same_user, only: [:edit, :update]
  
   
   def index
      @companies = Company.paginate(page: params[:page],per_page: 3)
   end
   
   def show
      
   end
   
   def new
      @company = Company.new
   end
   
   def create
      @company = Company.new(company_params)
      @company.user = current_user
      
      if @company.save
         flash[:success] = "Created Successfully!"
         redirect_to companies_path
      else
         render :new
      end
         
   end
   
   def edit
     
   end
   
   def update
      
      if @company.update(company_params)
         flash[:success] = "Updated Successfully!"
         redirect_to company_path(@company)
      else
         render :edit
      end
   end
   
   def like
      
      like = Like.create(like: params[:like], user: current_user, company: @company)
      if like.valid?
         flash[:success] = "You reviewed this company!"
      else 
         flash[:danger] = "You can only reviewed this company once!"
      end
      redirect_to likes_company_path(@company)
   end
   
   def user_likes
      
   end
   
   private
      def company_params
         params.require(:company).permit(:companyname,:date,:location,:package,:description,:picture,branch_ids: [])
      end
      
      def set_company
        @company = Company.find(params[:id])
     end
     
     def require_same_user
        if current_user != @company.user
           flash[:danger] = "You can only edit your own provided company info"
           redirect_to companies_path
        end
     end
     
     def require_user_likes
        if !logged_in?
           flash[:danger] = "You must be logged in to perform this action!"
           redirect_to :back
        end
     end
     
      def require_admin
        if !current_user.admin?
            flash[:danger] = "You must be an admin to perform this action!"
            redirect_to companies_path
        end
      end
end

app/views/companies/_form.html.erb
<%= render 'shared/errors', obj: @company %>

<div class="row">
    <div class = "col-md-6 col-md-offset-3 well" style="background-color: rgba(245, 245, 245, 0.3);">
        <% if @company.new_record? %>
        <strong><h3 class="text-center">Visiting Company Info</h3></strong>
        <% else %>
        <strong><h3 class="text-center">Edit Company Info</h3></strong>
        <% end %>
           <br><br>
        <%= form_for(@company, html: { multipart: true }) do |f| %>
         <%= f.label :company_Name %>  <%= f.text_field :companyname %>
         <%= f.label :date %>  <%= f.date_select(:date, :order => [:month, :day, :year]) %>
         <%= f.label :location %>  <%= f.text_field :location %>
         <%= f.label :package_in_Lakhs_Per_Annum %>  <%= f.number_field :package, :step => "0.01" %>
         <%= f.label :description %>  <%= f.text_area :description ,rows: 10%>
         
         <strong>Branches:</strong>
            <%= f.collection_check_boxes :branch_ids, Branch.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox"){cb.check_box(class: "checkbox") +  cb.text} %>
            <% end %>
        <br><br>
        
        
        <span class="picture">
            <%= f.file_field :picture,accept: 'image/jpeg,image/png,image/gif' %>
         </span>
        <%= f.submit(@company.new_record? ? 'Create Company' : 'Edit Company',class: "btn btn-warning") %>
        <% end %>
    </div>
</div>

<script type="text/javascript">
    $('#company_picture').bind('change',function() {
        size_in_megabytes=this.files[0].size/1024/1024;
        if (size_in_megabytes > 5) {
            alert('Maximum file size is 5MB. Please choose a smaller file');
        }
    });
</script> 

app/views/companies/edit.html.erb
<div style="padding-top: 50px;">
    <%= render 'layouts/navigationWithoutLogin' %>
</div>

<div>
    
    <div class="row">
        <strong><h3 class="text-center" style="margin-bottom: 10px"></h3></strong>
    </div>
    <img src="/assets/form.jpg" id="mybg" alt="background image">
    <%= render 'form' %>
    
</div>

app/views/companies/index.html.erb
<div style="padding-top: 50px;">
    <%= render 'layouts/navigationWithoutLogin' %>
</div>

<div style="background-image: url('/assets/header.jpg'">
    
<div style="padding-top: 50px;"></div>

<% @companies.each do |company| %>

<div class="container well">
	<div class="row">
		<div class="row"> 
                    <div class="col-xs-12 col-sm-3 col-md-3">
                        
                            <%= link_to image_tag(company.picture.url,size: "250x250", class: "gravatar img-responsive img-box img-thumbnail"),company_path(company) if company.picture? %>
                        
                    </div> 
                    <div class="col-xs-12 col-sm-9 col-md-9">
                        <div class="pull-right" style="margin-right: 7px; color: #FF4500">
                            <% case company.rating.round(2)  %>
                                <% when 1...2 %>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 20px;"></i>
                                <% when 2...3 %>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 20px;"></i>
                                <% when 3...4 %>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 20px;"></i>
                                <% when 4...5 %>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 20px;"></i>
                                <% when 5 %>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                    <i class="glyphicon glyphicon-star" style="font-size: 20px;"></i>
                                <% else %>
                                    Not Rated Yet
                            <% end %>
                        </div>
                        <div class="list-group">
                            <div class="list-group-item">
                                <div class="row-picture">
                                    <%= link_to gravatar_for(company.user, size: 100), user_path(company.user)%>
                                </div>
                                <div class="row-content">
                                    <div class="list-group-item-heading">
                                        <%= link_to company.companyname,company_path(company) %>
                                    </div>
                                    <small>
                                        <i class="glyphicon glyphicon-calendar"></i> Arriving on <%= company.date %> 
                                        <br>
                                        <span class="explore"><i class="glyphicon glyphicon-th"></i> <a style="text-decoration: none">Package: <%= company.package %> lpa </a></span>
                                    </small>
                                </div>
                            </div>
                        </div>
                        <p style="word-wrap: break-word; color: #55423E" class="well"><%= company.description %></p>
                        <% if company.branches.any? %><strong>For <%= render company.branches %> Branch</strong><% end %>
                        <div align="right" style="margin-right: 5px"><em>Brought to you by <strong><%= link_to company.user.username,user_path(company.user) %></strong></em></div>
                        
                    </div> 
        </div>
        
    </div>
</div>

<% end %>

<div class="pagniation-wrapper"> 
  <%= will_paginate %> 
</div>

<div style="padding-top: 50px;"></div>

</div>
        

app/views/companies/new.html.erb
<div style="padding-top: 50px;">
    <%= render 'layouts/navigationWithoutLogin' %>
</div>

<div>
    
    <div class="row">
        <strong><h3 class="text-center" style="margin-bottom: 10px"></h3></strong>
    </div>
    <img src="/assets/form.jpg" id="mybg" alt="background image">
    <%= render 'form' %>
    
</div>

app/views/companies/show.html.erb
<div style="padding-top: 50px;">
    <%= render 'layouts/navigationWithoutLogin' %>
</div>

<header>
    <div class="container">
        <div class="row " style="color: white;margin-bottom: 20px">
            <strong><h1 class="text-center" style="font-size: 50px; margin-bottom: 20px;" ><%= @company.companyname %></h1></strong>
            <div class="pull-left">
                <span class="btn btn-warning img-thumbnail" id="no_decoration" style="font-size: 12px; margin-right: 20px;margin-top: 25px"><%= link_to "Rated: " + @company.rating.round(2).to_s,likes_company_path(@company) %></span>
            </div>
            <div class="pull-left rating">
                <%= link_to like_company_path(@company, like: 5), method: :post do %>
                    &#9734;
                <% end %>
                
               <%= link_to like_company_path(@company, like: 4), method: :post do %>
                    &#9734;
                <% end %>
                
              <%= link_to like_company_path(@company, like: 3), method: :post do %>
                    &#9734;
                <% end %>
             
               <%= link_to like_company_path(@company, like: 2), method: :post do %>
                    &#9734; 
                <% end %>
               
                <%= link_to like_company_path(@company, like: 1), method: :post do %>
                    &#9734;
                <% end %>
             
            </div>
            
            <% if logged_in? and (current_user == @company.user) %>
                <%= link_to "Edit this info",edit_company_path(@company), class: "btn btn-danger pull-right" %>
             <% end %>
        </div>
        
        <div class="row" style="margin-top: 30px">
            <div class="col-sm-6">
                <%= image_tag(@company.picture.url,size: "400x400",class: "gravatar img-responsive img-circle") if @company.picture? %>
            </div>
            
            <div class="col-sm-1"></div>
           
            <div class="col-sm-5" style="margin-top: 5px; margin-bottom:5px">
                <div class="row well" style="background-color: rgba(245, 245, 245, 0);"><i class="glyphicon glyphicon-calendar"></i>&nbsp;&nbsp;Arriving on <%= @company.date %></div>
                <div class="row well" style="background-color: rgba(245, 245, 245, 0);"><i class="glyphicon glyphicon-th"></i>&nbsp;&nbsp;Package: <%= @company.package %> lakhs per annum</div>
                <% if @company.branches.any? %><div class="row well" style="background-color: rgba(245, 245, 245, 0);"><i class="glyphicon glyphicon-road"></i>&nbsp;&nbsp;For <%= render @company.branches %> Branch</div> <% end %>
                <div class="row well" style="background-color: rgba(245, 245, 245, 0);"><i class="glyphicon glyphicon-map-marker"></i>&nbsp;&nbsp;Location: <%= @company.location %></div>
            </div>
    
             
        </div>
        
        <div class="row" style="margin-top: 1px">
            <div class="col-sm-12">
                <em><h3 style="word-wrap: break-word; color: #ffffff"><%= simple_format(@company.description) %></h3></em>
            </div>
        </div>
        
    </div>
    
    <hr>
    
        
</header>

app/views/companies/user_likes.html.erb
div style="padding-top: 50px;">
    <%= render 'layouts/navigationWithoutLogin' %>
</div>

<div style="background-image: url('/assets/header.jpg'">
    
<div style="padding-top: 30px;"><h2 class="text-center" style="color: white; margin-bottom: 30px">Ratings for <em id="no_decoration"><%= link_to @company.companyname,company_path(@company) %></em></h2></div>


<header>
    <div class="container">
        <% @company.likes.each do |l|  %>
        <div class="row well" style="background-color: rgba(245, 245, 245, 0.3);">
            <div class="col-sm-1 col-sm-offset-1">
                <%= link_to gravatar_for(l.user, size: 70), user_path(l.user), class: "img-circle" %>
            </div>
            <div class="col-sm-2" style="font-size: 20px; margin-top: 20px" id="no_decoration">
                <%= link_to l.user.username,user_path(l.user) %>
            </div>
            <div class="col-sm-5" style="color: #ffd700">
                <% case l.like  %>
                                <% when 1...2 %>
                                    <i class="glyphicon glyphicon-star" style="font-size: 60px;"></i>&nbsp;&nbsp;&nbsp;
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 60px;"></i>&nbsp;&nbsp;&nbsp;
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 60px;"></i>&nbsp;&nbsp;&nbsp;
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 60px;"></i>&nbsp;&nbsp;&nbsp;
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 60px;"></i>&nbsp;&nbsp;&nbsp;
                                <% when 2...3 %>
                                    <i class="glyphicon glyphicon-star" style="font-size: 60px;"></i>&nbsp;&nbsp;&nbsp;
                                    <i class="glyphicon glyphicon-star" style="font-size: 60px;"></i>&nbsp;&nbsp;&nbsp;
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 60px;"></i>&nbsp;&nbsp;&nbsp;
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 60px;"></i>&nbsp;&nbsp;&nbsp;
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 60px;"></i>&nbsp;&nbsp;&nbsp;
                                <% when 3...4 %>
                                    <i class="glyphicon glyphicon-star" style="font-size: 60px;"></i>&nbsp;&nbsp;&nbsp;
                                    <i class="glyphicon glyphicon-star" style="font-size: 60px;"></i>&nbsp;&nbsp;&nbsp;
                                    <i class="glyphicon glyphicon-star" style="font-size: 60px;"></i>&nbsp;&nbsp;&nbsp;
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 60px;"></i>&nbsp;&nbsp;&nbsp;
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 60px;"></i>&nbsp;&nbsp;&nbsp;
                                <% when 4...5 %>
                                    <i class="glyphicon glyphicon-star" style="font-size: 60px;"></i>&nbsp;&nbsp;&nbsp;
                                    <i class="glyphicon glyphicon-star" style="font-size: 60px;"></i>&nbsp;&nbsp;&nbsp;
                                    <i class="glyphicon glyphicon-star" style="font-size: 60px;"></i>&nbsp;&nbsp;&nbsp;
                                    <i class="glyphicon glyphicon-star" style="font-size: 60px;"></i>&nbsp;&nbsp;&nbsp;
                                    <i class="glyphicon glyphicon-star-empty" style="font-size: 60px;"></i>&nbsp;&nbsp;&nbsp;
                                <% when 5 %>
                                    <i class="glyphicon glyphicon-star" style="font-size: 60px;"></i>&nbsp;&nbsp;&nbsp;
                                    <i class="glyphicon glyphicon-star" style="font-size: 60px;"></i>&nbsp;&nbsp;&nbsp;
                                    <i class="glyphicon glyphicon-star" style="font-size: 60px;"></i>&nbsp;&nbsp;&nbsp;
                                    <i class="glyphicon glyphicon-star" style="font-size: 60px;"></i>&nbsp;&nbsp;&nbsp;
                                    <i class="glyphicon glyphicon-star" style="font-size: 60px;"></i>&nbsp;&nbsp;&nbsp;
                            <% end %>
            </div>
            
            <div class="col-sm-3">
                <span class="btn btn-warning img-thumbnail" style="font-size: 15px;margin-top: 18px" >Rated: <%= l.like.round(2) %></span>
            </div>
           
        </div>
        
        <% end %>
    <hr>
    
    </div>    
</header>