config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/home', to: 'pages#home'
  post '/home', to: 'pages#create'
  get '/logout', to: 'pages#destroy'
  
  resources :companies do
    member do
      post 'like'
      get '/likes', to: 'companies#user_likes'
    end
  end
  
  resources :users, except: [:new,:index, :destroy]
  get '/register', to: 'users#new'
  
  resources :branches, only: [:new, :create, :show]
  
  
end

app/views/layouts/_messages.html.erb
<% flash.each do |message_type,message| %>
    <% if message_type === "success" %>
        <div id="note" style="background: #DFF0D8">
             <%= message %><a id="close">[close]</a>
        </div>
    <% else %>
        <div id="note" style="background: #F2DEDE">
             <%= message %><a id="close">[close]</a>
        </div>
    <% end %>
<% end %>

<script>
   close = document.getElementById("close");
   close.addEventListener('click', function() {
     note = document.getElementById("note");
     note.style.display = 'none';
   }, false);
</script>

app/views/layouts/_navigation.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
              
                <%= link_to "PlaceMentor",home_path, class: "navbar-brand page-scroll" %>

            </div>

            
            <%= link_to "Login",class: "navbar-brand pull-right dropdown-toggle verticalLine hovering", "data-toggle" => "dropdown", :style=>"margin-right: 1px; color: #F05F40;font-weight:bold" do %>
            Login <b class="caret"></b>
            <% end %>
            
                <ul id="dropdown-login" class="dropdown-menu pull-right well" style="padding: 5px 10px 0px 10px; margin-right: 25px; background-color: rgba(256, 256, 256, 0);">
                   <%= form_tag '/home' do %>
                  <li>
                    <div class="control-group " style="margin:5px; ">
                       <i class="glyphicon glyphicon-user myBorderGlyphicons" style="font-size:15px;padding: 5px;color: #F05F40"></i>
                        <div class="controls myBorder" style="height: 26px; display: inline-block;">
                           <%= text_field_tag :email %>
                        </div>
                    </div>
                  </li>
                  <li>
                    <div class="control-group" style="margin:5px">
                        <i class="glyphicon glyphicon-lock myBorderGlyphicons" style="font-size:15px;padding: 5px;color: #F05F40"></i>
                        <div class="controls myBorder" style="height: 26px;display: inline-block;">
                           <%= password_field_tag :password %>
                        </div>
                    </div>
                  </li>
     
                  <li style="margin:5px;">
                    <%= submit_tag 'Sign in', class: "btn orangebg" %>
                  </li>
                   <% end %>
                </ul>
                



        </div>
        <!-- /.container-fluid -->
    </nav>
    
   

app/views/layouts/_navigationWithoutLogin.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top" >
        <div class="container-fluid" style="background-image: url('/assets/header.jpg'">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                
                  
                <%= link_to "PlaceMentor",home_path, class: "navbar-brand page-scroll" %>
                
                
            </div>
          
            <% if logged_in? %>
                <% if current_user.admin? %>
                <div  class="nav_item">
                    <%= link_to "[ New Company Visiting? ]",new_company_path,class: "navbar-brand pull-left verticalLine hovering", :style=> "margin-left: 10px; color: #F05F40;font-weight:bold" %>
                </div>
                <% end %>
                
                <ul class="nav_item">
                    <li class="dropdown">
                      <%= link_to '#',class: "navbar-brand pull-right dropdown-toggle verticalLine hovering", "data-toggle" => "dropdown", :style=>"margin-right: 1px; color: #F05F40;font-weight:bold" do %>
                        <%= current_user.username %> <b class="caret"></b>
                      <% end %>
                        <ul class='dropdown-menu pull-right'>
                            <li><%= link_to "View Profile",user_path(current_user) %></li>
                            <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
                            <li class="divider"></li>
                            <li><%= link_to "Logout",logout_path %></li>
                        </ul>
                    </li>
                </ul>
                
                
            <% end %>
            
            
            
            
            
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlaceMentor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <%= google_webfonts_init({
    google: ['Open+Sans', 'Merriweather']
  }) %>
  
</head>
<body id="page-top" >
  
  
<%= render 'layouts/messages' %>
<%= yield %>

</body>
</html>